plugins {
    id 'com.android.application'
}

android {
    namespace 'site.doeacho.royalsmash'
    compileSdk 35

    defaultConfig {
        applicationId 'site.doeacho.royalsmash'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '1.1.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

}

dependencies {
    implementation 'androidx.webkit:webkit:1.12.1'
}
